steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/microservices-devtallers/image-registry/products-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/microservices-devtallers/image-registry/products-ms",
      ]